profile: default
region: ap-northeast-1
versioning: false
default_alias: null
clean_build: false
configuration:
  name: mylambda
  runtime: python3.6
  role: arn:aws:iam::xxxxxxxxxxxx:role/test-lambda
  handler: lambda_function.lambda_handler
  description: This is a sample lambda function.
  timeout: 10
  memory_size: 128
  # vpc_config:
  #   subnets:
  #   - subnet-xxxxxxxx
  #   security_groups:
  #   - sg-xxxxxxxx
